modLoader="javafml"
loaderVersion="[45,)"
license="GNU General Public License v3.0"
displayURL="https://www.curseforge.com/minecraft/mc-mods/stabx-modern-guns"

[[mods]]
    modId="stabxmodernguns"
    version="7.0"
    displayName="Stabx Modern Guns"
    authors="Stabilizer King"
    credits="Stabilizer king and big thanks to Stabx modding discord members"
    description="Addon for Mr.Crayfish's gun mod adding High Quality and Realistic guns with better sounds"
    updateJSONURL="https://github.com/Stabilizer360/Stabx_Modern_Guns_1.19.4/blob/master/update.json"

[[dependencies.stabxmodernguns]]
    modId="forge"
    mandatory=true
    versionRange="[45.1.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stabxmodernguns]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stabxmodernguns]]
    modId="cgm"
    mandatory=true
    versionRange="[1.3.7,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stabxmodernguns]]
    modId="framework"
    mandatory=true
    versionRange="[0.6.16,)"
    ordering="NONE"
    side="BOTH"

[modproperties.stabxmodernguns]
    catalogueItemIcon="stabxmodernguns:m4"
