modLoader="javafml"
loaderVersion="[45,)"
license="GNU General Public License v3.0"

[[mods]]
    modId="stabxmodernguns"
    version="6.2"
    displayName="Stabx Modern Guns"
    authors="Stabilizer King"
    credits="Stabx Community Big thanks to Comrede Micky for making the gk57"
    description="Addon for Mr.Crayfish's gun mod adding High Quality and Realistic guns with better sounds"

[[dependencies.stabxmodernguns]]
    modId="forge"
    mandatory=true
    versionRange="[45.1.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stabxmodernguns]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stabxmodernguns]]
    modId="cgm"
    mandatory=true
    versionRange="[1.3.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stabxmodernguns]]
    modId="framework"
    mandatory=true
    versionRange="[0.4.2,)"
    ordering="NONE"
    side="BOTH"


[modproperties.stabxmodernguns]
    catalogueItemIcon="stabxmodernguns:m4"
